#!/usr/bin/env sh

for folder in "$@"
do
    mkdir -p "$HOME/ramos/$folder/clases/files"

    cp "../.gitignore"         "$HOME/ramos/$folder/"
    cp "apuntes.cls"           "$HOME/ramos/$folder/clases/"
    cp "main.tex"              "$HOME/ramos/$folder/clases/"
    cp "create-subfile.sh"     "$HOME/ramos/$folder/clases/"
    cp "fancy-dates.sty"       "$HOME/ramos/$folder/clases/"
    cp "math-environments.sty" "$HOME/ramos/$folder/clases/"
    cp "math-macros.sty"       "$HOME/ramos/$folder/clases/"
    cp ".latexmkrc"            "$HOME/ramos/$folder/clases/"
    cp ".latexmkrc"            "$HOME/ramos/$folder/clases/files/"
    cp "files/template.tex"    "$HOME/ramos/$folder/clases/files/"
done
